### ISSUE TITLE
release for Scala 2.13.0-M5?

### ISSUE THREAD

**Issue by SethTisue** [playframework/twirl#184]
judging from e.g. https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1284/consoleFull , it might be just one compilation error away from working:

```
[twirl] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.12/project-builds/twirl-03ab26d55d6d23293315583edf1f4f4d43493d44/compiler/src/main/scala/play/twirl/compiler/TwirlCompiler.scala:508: method printMessage overrides nothing
[twirl] [error]           override def printMessage(pos: Position, msg: String) = ()
[twirl] [error]                        ^
```

looks like this is running afoul of some compiler stuff we refactored in 2.13

plus of course 2.13 would need to be added to the build, CI matrix, etc.

## Dependencies:

- [x] https://github.com/scala-js/scala-js/issues/3443
- [x] https://github.com/scalatest/scalatest/issues/1409

**Comment by SethTisue** [comment]
@marcospereira this might be an easy-ish one, either for your team, or for an open source volunteer

**Comment by marcospereira** [comment]
Yep, sounds like a small one.

Edited the description to list the dependencies.

**Comment by SethTisue** [comment]
ScalaTest is now available for M5 on both JVM & JS

**Comment by marcospereira** [comment]
Not yet. There is a problem with Scala JS (or Node, I need to investigate better) in our release process.

**Comment by SethTisue** [comment]
@marcospereira link to the log...? maybe it's something I'd recognize

**Comment by marcospereira** [comment]
I don't have a place to link, but here is what I got:

## Before Updating

Was using node 4.2.x here:

```
[stdin]:46
  var inBuffer = Buffer.alloc(0);
                        ^

TypeError: Buffer.alloc is not a function
    at [stdin]:46:25
    at [stdin]:112:4
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:410:26)
    at node.js:578:27
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)

org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
	at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.waitForVM(ExternalJSEnv.scala:114)
	at org.scalajs.jsenv.ExternalJSEnv$AsyncExtRunner$$anon$1$$anonfun$2.apply$mcV$sp(ExternalJSEnv.scala:179)
	at org.scalajs.jsenv.ExternalJSEnv$AsyncExtRunner$$anon$1$$anonfun$2.apply(ExternalJSEnv.scala:179)
	at org.scalajs.jsenv.ExternalJSEnv$AsyncExtRunner$$anon$1$$anonfun$2.apply(ExternalJSEnv.scala:179)
	at scala.util.Try$.apply(Try.scala:161)
	at org.scalajs.jsenv.ExternalJSEnv$AsyncExtRunner$$anon$1.run(ExternalJSEnv.scala:179)
[error] (apiJS/test:loadedTestFrameworks) org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
```


## After Updating

Tried with node 8 and 10 with this same error:

```
[info] /tmp/sbt_74c080db/scalajs-compile/target/scala-2.10/root-fastopt.js:9423
[info] function $as_sc_GenTraversable(obj) {
[info]                               ^
[info]
[info] RangeError: Maximum call stack size exceeded
[info]     at $as_sc_GenTraversable (/tmp/sbt_74c080db/scalajs-compile/target/scala-2.10/root-fastopt.js:9423:31)
[info]     at $c_scg_GenTraversableFactory$ReusableCBF.$c_scg_GenTraversableFactory$GenericCanBuildFrom.apply__O__scm_Builder (/tmp/sbt_74c080db/scalajs-compile/target/scala-2.10/root-fastopt.js:5450:16)
[info]     at $s_sc_TraversableLike$class__builder$1__p0__sc_TraversableLike__scg_CanBuildFrom__scm_Builder (/tmp/sbt_74c080db/scalajs-compile/target/scala-2.10/root-fastopt.js:1719:16)
[info]     at $s_sc_TraversableLike$class__map__sc_TraversableLike__F1__scg_CanBuildFrom__O (/tmp/sbt_74c080db/scalajs-compile/target/scala-2.10/root-fastopt.js:1710:11)
[info]     at $c_s_xml_Elem.$c_sc_AbstractTraversable.map__F1__scg_CanBuildFrom__O (/tmp/sbt_74c080db/scalajs-compile/target/scala-2.10/root-fastopt.js:13949:10)
[info]     at $c_Lhtml_xml$undtest$.$c_Lplay_twirl_api_BaseScalaTemplate.$$unddisplay$und__O__s_reflect_ClassTag__Lplay_twirl_api_Appendable (/tmp/sbt_74c080db/scalajs-compile/target/scala-2.10/root-fastopt.js:8740:37)
[info]     at /tmp/sbt_74c080db/scalajs-compile/target/scala-2.10/root-fastopt.js:8736:28
[info]     at $c_sjsr_AnonFunction1.apply__O__O (/tmp/sbt_74c080db/scalajs-compile/target/scala-2.10/root-fastopt.js:7076:23)
[info]     at /tmp/sbt_74c080db/scalajs-compile/target/scala-2.10/root-fastopt.js:1713:48
[info]     at $c_sjsr_AnonFunction1.apply__O__O (/tmp/sbt_74c080db/scalajs-compile/target/scala-2.10/root-fastopt.js:7076:23)
[info] org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
[info] 	at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.waitForVM(ExternalJSEnv.scala:114)
[info] 	at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:164)
[info] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:792)
[info] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$76$$anonfun$apply$52$$anonfun$apply$53.apply(ScalaJSPluginInternal.scala:944)
[info] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$76$$anonfun$apply$52$$anonfun$apply$53.apply(ScalaJSPluginInternal.scala:938)
[info] 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
```

I wonder if this is a problem with Scala.js or if we need to configure node [stack-size](https://stackoverflow.com/questions/11332422/how-can-i-increase-the-maximum-call-stack-size-in-node-js).

**Comment by SethTisue** [comment]
I'm afraid I have no insight into the Scala.js issue. If you're still stuck on it, consider pinging Sébastien about it, I don't think we've bothered him often in the past about Lightbend stuff.

This isn't urgent at the moment, but the Akka team is moving forward again on M5 support, and once Akka publishes for M5, a bunch of Play/Lagom stuff will unbecome unblocked, so it might make sense to get this one out of the way ahead of time.

**Comment by marcospereira** [comment]
Hey, @SethTisue. We now have an M5 release here:

http://repo1.maven.org/maven2/com/typesafe/play/twirl-api_2.13.0-M5/

We were having problems with old versions of node. After updating, we were able to release again.

**Comment by SethTisue** [comment]
awesome!

scala/make-release-notes@2c6a61c931ef0353d9a2fc4775d3d5d069fba8ff
