### ISSUE TITLE
args block parsing broken when there are 2 open parenthesis

### ISSUE THREAD

**Issue by xuwei-k** [playframework/twirl#232]
### change `blockWithTuple.scala.html` test as follows

```diff
diff --git a/compiler/src/test/resources/blockWithTuple.scala.html b/compiler/src/test/resources/blockWithTuple.scala.html
index da81c4a..d1adf91 100644
--- a/compiler/src/test/resources/blockWithTuple.scala.html
+++ b/compiler/src/test/resources/blockWithTuple.scala.html
@@ -1,5 +1,5 @@
 @(args: Seq[(String, String)])
 
-@args.map { case (k, v) =>
+@args.zipWithIndex.map { case ((k, v), index) =>
     @k => @v
 }
\ No newline at end of file
diff --git a/compiler/src/test/scala/play/twirl/compiler/test/CompilerSpec.scala b/compiler/src/test/scala/play/twirl/compiler/test/CompilerSpec.scala
index dc39759..ce58c25 100644
--- a/compiler/src/test/scala/play/twirl/compiler/test/CompilerSpec.scala
+++ b/compiler/src/test/scala/play/twirl/compiler/test/CompilerSpec.scala
@@ -326,6 +326,9 @@ object Helper {
 
       compileErrors.headOption.foreach {
         case CompilationError(msg, line, column) => {
+
+          // for debug
+          println(scala.io.Source.fromFile(generated).getLines.mkString("\n"))
+
           compileErrors.clear()
           throw CompilationError(msg, mapper.mapLine(line), mapper.mapPosition(column))
         }
```

#### `sbt compiler/test` log

```
[info] - compile successfully (block with tuple) *** FAILED ***
[info]   play.twirl.compiler.test.Helper$CompilationError: not found: value k
[info]   at play.twirl.compiler.test.Helper$CompilerHelper.$anonfun$compile$1(CompilerSpec.scala:333)
[info]   at scala.Option.foreach(Option.scala:274)
[info]   at play.twirl.compiler.test.Helper$CompilerHelper.compile(CompilerSpec.scala:327)
[info]   at play.twirl.compiler.test.CompilerSpec.$anonfun$new$35(CompilerSpec.scala:236)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$3.apply(WordSpecLike.scala:1075)
```

### generated code

```scala
  /**/
  def apply/*1.2*/(args: Seq[(String, String)]):play.twirl.api.HtmlFormat.Appendable = {
    _display_ {
      {


Seq[Any](format.raw/*2.1*/("""
"""),_display_(/*3.2*/args/*3.6*/.zipWithIndex.map/*3.23*/ {_display_(Seq[Any](format.raw/*3.25*/(""" case ((k, v), index) =>
    """),_display_(/*4.6*/k),format.raw/*4.7*/(""" """),format.raw/*4.8*/("""=> """),_display_(/*4.12*/v),format.raw/*4.13*/("""
""")))}))
      }
    }
  }
```

### note

I think this fix is not perfect 😢 

https://github.com/playframework/twirl/commit/0ae33fd69c3b7772862727e1d2a61d80edf6a403#diff-39fe3e23b24661c010fa60bbd03b55c5R499

**Comment by renatocaval** [comment]
Thanks @xuwei-k for reporting.

I created a PR to fix it, #233. 

The change in https://github.com/playframework/twirl/commit/0ae33fd69c3b7772862727e1d2a61d80edf6a403#diff-39fe3e23b24661c010fa60bbd03b55c5R499 was indeed not needed and could be removed.
