### ISSUE TITLE
sbt-twirl version 1.5.0 is incompatible with sbt 1.5.0 (NoClassDefFoundError)

### ISSUE THREAD

**Issue by alexandru** [playframework/twirl#412]
Using `sbt-twirl` version `1.5.0` and tried upgrading to sbt `1.5.0`.

I'm getting this error on compilation, which seems to be some sort of binary compatibility issue:

```
[error] java.lang.NoClassDefFoundError: Could not initialize class play.twirl.compiler.TwirlCompiler$TemplateAsFunctionCompiler$PresentationCompiler$
[error] 	at play.twirl.compiler.TwirlCompiler$TemplateAsFunctionCompiler$.getFunctionMapping(TwirlCompiler.scala:537)
[error] 	at play.twirl.compiler.TwirlCompiler$.generateCode(TwirlCompiler.scala:429)
[error] 	at play.twirl.compiler.TwirlCompiler$.generateFinalTemplate(TwirlCompiler.scala:487)
[error] 	at play.twirl.compiler.TwirlCompiler$.parseAndGenerateCode(TwirlCompiler.scala:259)
[error] 	at play.twirl.compiler.TwirlCompiler$.compile(TwirlCompiler.scala:200)
[error] 	at play.twirl.sbt.TemplateCompiler$.$anonfun$compile$2(TemplateCompiler.scala:60)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
[error] 	at play.twirl.sbt.TemplateCompiler$.compile(TemplateCompiler.scala:50)
[error] 	at play.twirl.sbt.SbtTwirl$.$anonfun$compileTemplatesTask$1(SbtTwirl.scala:111)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mkurz** [comment]
Please use twirl `1.5.1`.
